# Generated by Django 4.0.1 on 2022-01-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('phoneNumber', models.CharField(max_length=20, null=True)),
                ('mobilePhoneNumber', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
