# Generated by Django 4.0.1 on 2022-02-03 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('visibility', models.BooleanField()),
                ('password', models.CharField(max_length=100, null=True)),
                ('content', models.TextField()),
                ('file', models.FileField(null=True, upload_to='media/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.user')),
            ],
            options={
                'db_table': 'notice',
            },
        ),
    ]
