# Generated by Django 4.0.1 on 2022-02-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='visibility',
            field=models.CharField(choices=[('public', '공개'), ('private', '비공개')], max_length=10),
        ),
    ]
