# Generated by Django 4.0.2 on 2022-02-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_remove_notice_file_notice_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='watched',
            field=models.IntegerField(default=0),
        ),
    ]
