# Generated by Django 4.0.2 on 2022-02-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_rename_master_notice_attachment_master_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice_attachment',
            old_name='master_notice',
            new_name='notice',
        ),
    ]
