# Generated by Django 4.0.2 on 2022-02-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0008_notice_attachment_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='hasAttachment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
