# Generated by Django 4.0.2 on 2022-02-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0010_remove_notice_hasattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='password',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
