# Generated by Django 4.0.2 on 2022-02-04 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_created=True, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='media/')),
                ('content', models.TextField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab', to='account.user')),
            ],
        ),
    ]
