# Generated by Django 4.0.2 on 2022-02-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_alter_lab_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='file',
            field=models.FileField(null=True, upload_to='file/'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
