# Generated by Django 4.0.2 on 2022-02-05 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_lab_file_alter_lab_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lab',
            table='lab',
        ),
    ]
