# Generated by Django 4.0.2 on 2022-02-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_alter_lab_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
