# Generated by Django 4.0.2 on 2022-02-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_alter_lab_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lab',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
